spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: test
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: atomicHibernateSeqquence